export const CH = {
  AUTH_SIGN_IN: 'desktop:auth:sign-in',
  AUTH_SIGN_OUT: 'desktop:auth:sign-out',
  AUTH_STATUS: 'desktop:auth:status',

  GW_DEVICES: 'desktop:gateway:devices',
  GW_START_SESSION: 'desktop:gateway:start-session',
  GW_SEND_MESSAGE: 'desktop:gateway:send-message',
  GW_MEDIATION_COMMAND: 'desktop:gateway:mediation-command',
  GW_END_SESSION: 'desktop:gateway:end-session',
  GW_SHARE_CONSUME: 'desktop:gateway:share-consume',
  GW_SHARE_CREATE: 'desktop:gateway:share-create',
  GW_SHARE_LIST_GRANTS: 'desktop:gateway:share-list-grants',
  GW_SHARE_REVOKE: 'desktop:gateway:share-revoke',
  GW_SHARE_LEAVE: 'desktop:gateway:share-leave',

  MEDIATION_CREATE: 'desktop:mediation:create',
  MEDIATION_GET: 'desktop:mediation:get',
  MEDIATION_LIST: 'desktop:mediation:list',
  MEDIATION_JOIN: 'desktop:mediation:join',
  MEDIATION_APPEND_PRIVATE: 'desktop:mediation:append-private',
  MEDIATION_COACH_REPLY: 'desktop:mediation:coach-reply',
  MEDIATION_SET_CONSENT: 'desktop:mediation:set-consent',
  MEDIATION_SET_PRIVATE_SUMMARY: 'desktop:mediation:set-private-summary',
  MEDIATION_RUN_INTAKE_TEMPLATE: 'desktop:mediation:run-intake-template',
  MEDIATION_SET_READY: 'desktop:mediation:set-ready',
  MEDIATION_SEND_DIRECT: 'desktop:mediation:send-direct',
  MEDIATION_CREATE_DRAFT: 'desktop:mediation:create-draft',
  MEDIATION_APPEND_DRAFT: 'desktop:mediation:append-draft',
  MEDIATION_SUGGEST_DRAFT: 'desktop:mediation:suggest-draft',
  MEDIATION_RUN_DRAFT_SUGGESTION: 'desktop:mediation:run-draft-suggestion',
  MEDIATION_APPROVE_DRAFT: 'desktop:mediation:approve-draft',
  MEDIATION_REJECT_DRAFT: 'desktop:mediation:reject-draft',
  MEDIATION_RESOLVE: 'desktop:mediation:resolve',
  MEDIATION_CLOSE: 'desktop:mediation:close',
  MEDIATION_REMOTE_COMMAND: 'desktop:mediation:remote-command',
  MEDIATION_REMOTE_GRANT_CASE: 'desktop:mediation:remote-grant-case',
  MEDIATION_REMOTE_TERMINATE_GRANT: 'desktop:mediation:remote-terminate-grant',
  MEDIATION_SYNC_REMOTE_CASE: 'desktop:mediation:sync-remote-case',
  MEDIATION_MARK_REMOTE_GRANT_STATUS: 'desktop:mediation:mark-remote-grant-status',
  MEDIATION_REMOVE_REMOTE_CASE: 'desktop:mediation:remove-remote-case',

  ROOM_CREATE: 'desktop:room:create',
  ROOM_PAUSE: 'desktop:room:pause',
  ROOM_RESUME: 'desktop:room:resume',
  ROOM_STOP: 'desktop:room:stop',
  ROOM_STATUS: 'desktop:room:status',
  ROOM_EDIT_STATE: 'desktop:room:edit-state',
  ROOM_APPROVE: 'desktop:room:approve',
  ROOM_PLUGIN_LIST: 'desktop:room:plugin-list',

  INTERFACES_LIST: 'desktop:interfaces:list',
  INTERFACES_CREATE_SLACK: 'desktop:interfaces:create-slack',
  INTERFACES_UPDATE: 'desktop:interfaces:update',
  INTERFACES_DELETE: 'desktop:interfaces:delete',
  INTERFACES_ROTATE_TOKEN: 'desktop:interfaces:rotate-token',
  INTERFACES_GET_WEBHOOK_URL: 'desktop:interfaces:get-webhook-url',
  INTERFACES_RUNTIME_STATUS: 'desktop:interfaces:runtime-status',
  INTERFACES_SYNC: 'desktop:interfaces:sync',

  OUT_MEDIATION_EVENT: 'desktop:mediation-event',
  OUT_ROOM_EVENT: 'desktop:room-event',
  OUT_ROOM_METRICS: 'desktop:room-metrics',
  OUT_AUTH_CHANGED: 'desktop:auth-changed',
  OUT_GATEWAY_CHAT_EVENT: 'desktop:gateway-chat-event',
  OUT_GATEWAY_SHARE_EVENT: 'desktop:gateway-share-event',
  OUT_GATEWAY_DEVICE_EVENT: 'desktop:gateway-device-event',
} as const;

export type ChannelName = (typeof CH)[keyof typeof CH];
